title: Dog Years
description: Short stories by Julio
author: Julio
email: thinmanj@gmail.com
baseurl: /dog-years-stories
url: https://thinmanj.github.io

theme: minima
markdown: kramdown

collections:
  stories:
    output: true
    permalink: /stories/:title/

defaults:
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "post"
